/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The CountResponse model module.
 * @module model/CountResponse
 * @version 0.0.1
 */
export default class CountResponse {
  /**
   * Constructs a new <code>CountResponse</code>.
   * Counts of entities matching a faceted search.
   * @alias module:model/CountResponse
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>CountResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CountResponse} obj Optional instance to populate.
   * @return {module:model/CountResponse} The populated <code>CountResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CountResponse();

      if (data.hasOwnProperty("donor_count")) {
        obj["donor_count"] = ApiClient.convertToType(
          data["donor_count"],
          "Number"
        );
      }
      if (data.hasOwnProperty("file_count")) {
        obj["file_count"] = ApiClient.convertToType(
          data["file_count"],
          "Number"
        );
      }
    }
    return obj;
  }

  /**
   * @member {Number} donor_count
   */
  donor_count = undefined;
  /**
   * @member {Number} file_count
   */
  file_count = undefined;
}
