/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ListValue from "./ListValue";

/**
 * The FacetValue model module.
 * @module model/FacetValue
 * @version 0.0.1
 */
export default class FacetValue {
  /**
   * Constructs a new <code>FacetValue</code>.
   * @alias module:model/FacetValue
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>FacetValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacetValue} obj Optional instance to populate.
   * @return {module:model/FacetValue} The populated <code>FacetValue</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FacetValue();

      if (data.hasOwnProperty("value_type")) {
        obj["value_type"] = ApiClient.convertToType(
          data["value_type"],
          "String"
        );
      }
      if (data.hasOwnProperty("values")) {
        obj["values"] = ApiClient.convertToType(data["values"], [ListValue]);
      }
      if (data.hasOwnProperty("low")) {
        obj["low"] = ApiClient.convertToType(data["low"], "Number");
      }
      if (data.hasOwnProperty("high")) {
        obj["high"] = ApiClient.convertToType(data["high"], "Number");
      }
      if (data.hasOwnProperty("count")) {
        obj["count"] = ApiClient.convertToType(data["count"], "Number");
      }
    }
    return obj;
  }

  /**
   * @member {String} value_type
   */
  value_type = undefined;
  /**
   * @member {Array.<module:model/ListValue>} values
   */
  values = undefined;
  /**
   * @member {Number} low
   */
  low = undefined;
  /**
   * @member {Number} high
   */
  high = undefined;
  /**
   * @member {Number} count
   */
  count = undefined;
}
