/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The Facet model module.
 * @module model/Facet
 * @version 0.0.1
 */
export default class Facet {
  /**
   * Constructs a new <code>Facet</code>.
   * Information about a field exposed to search.
   * @alias module:model/Facet
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>Facet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Facet} obj Optional instance to populate.
   * @return {module:model/Facet} The populated <code>Facet</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Facet();

      if (data.hasOwnProperty("facet_type")) {
        obj["facet_type"] = ApiClient.convertToType(
          data["facet_type"],
          "String"
        );
      }
      if (data.hasOwnProperty("display_name")) {
        obj["display_name"] = ApiClient.convertToType(
          data["display_name"],
          "String"
        );
      }
      if (data.hasOwnProperty("db_name")) {
        obj["db_name"] = ApiClient.convertToType(data["db_name"], "String");
      }
      if (data.hasOwnProperty("values")) {
        obj["values"] = ApiClient.convertToType(data["values"], ["String"]);
      }
      if (data.hasOwnProperty("min")) {
        obj["min"] = ApiClient.convertToType(data["min"], "Number");
      }
      if (data.hasOwnProperty("max")) {
        obj["max"] = ApiClient.convertToType(data["max"], "Number");
      }
    }
    return obj;
  }

  /**
   * @member {String} facet_type
   */
  facet_type = undefined;
  /**
   * @member {String} display_name
   */
  display_name = undefined;
  /**
   * @member {String} db_name
   */
  db_name = undefined;
  /**
   * @member {Array.<String>} values
   */
  values = undefined;
  /**
   * @member {Number} min
   */
  min = undefined;
  /**
   * @member {Number} max
   */
  max = undefined;
}
