/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The ListValue model module.
 * @module model/ListValue
 * @version 0.0.1
 */
export default class ListValue {
  /**
   * Constructs a new <code>ListValue</code>.
   * A facet value, for example, \&quot;Male\&quot;/34.
   * @alias module:model/ListValue
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>ListValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListValue} obj Optional instance to populate.
   * @return {module:model/ListValue} The populated <code>ListValue</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListValue();

      if (data.hasOwnProperty("name")) {
        obj["name"] = ApiClient.convertToType(data["name"], "String");
      }
      if (data.hasOwnProperty("count")) {
        obj["count"] = ApiClient.convertToType(data["count"], "Number");
      }
    }
    return obj;
  }

  /**
   * Facet value name, for example, \"Male\".
   * @member {String} name
   */
  name = undefined;
  /**
   * Facet value count.
   * @member {Number} count
   */
  count = undefined;
}
