#!/usr/bin/env bash
set -euo pipefail

declare -r SECRETS_PREFIX=secret/dsde/monster/prod/encode
declare -r CAAS_KEY_PATH=${SECRETS_PREFIX}/caas-runner-key.json
declare -r CAAS_OPTIONS_PATH=${SECRETS_PREFIX}/caas-options.json

function usage () {
  cat <<EOF >&2
Usage: $0 <base-cromwell-options-json>

Injects secrets needed for submitting workflows to CaaS into Cromwell options JSON.

Requires 'vault' and 'jq'
EOF
}

function vault_read () {
  vault read -format=json $1 | jq -c .data
}

function merge_json () {
  jq -s add ${@}
}

function main () {
  if [ $# != 1 ]; then
    usage
    exit 1
  fi

  local -r key_tmp=$(mktemp -t caas-key)
  local -r user_tmp=$(mktemp -t user-tmp)
  local -r options_tmp=$(mktemp -t caas-options)
  trap "rm -f '${key_tmp}' '${user_tmp}' '${options_tmp}'" ERR EXIT HUP TERM INT

  vault_read ${CAAS_OPTIONS_PATH} > ${options_tmp}
  vault_read ${CAAS_KEY_PATH} > ${key_tmp}
  echo '{"user_service_account_json":'$(jq '@text' ${key_tmp})'}' > ${user_tmp}

  merge_json ${options_tmp} $1 ${user_tmp}
}

main ${@}
