pipeline {
    agent any
    environment {
        PATH = "${tool('sbt')}:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                sh 'sbt compile'
            }
        }
    }
}
