runtime: custom
env: flex

readiness_check:
  path: "/api/count"
  check_interval_sec: 30
  timeout_sec: 1
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 30

liveness_check:
  path: "/api/facets"
  check_interval_sec: 30
  timeout_sec: 2
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 30
