/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import CountResponse from "../model/CountResponse";

/**
 * Count service.
 * @module api/CountApi
 * @version 0.0.1
 */
export default class CountApi {
  /**
   * Constructs a new CountApi.
   * @alias module:api/CountApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the countGet operation.
   * @callback module:api/CountApi~countGetCallback
   * @param {String} error Error message, if any.
   * @param {module:model/CountResponse} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get the number of records matching selected filters.
   * @param {Object} opts Optional parameters
   * @param {Array.<String>} opts.filter Encoded form of facet values selected in the UI.
   * @param {module:api/CountApi~countGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/CountResponse}
   */
  countGet(opts, callback) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      filter: this.apiClient.buildCollectionParam(opts["filter"], "pipes")
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = [];
    let returnType = CountResponse;

    return this.apiClient.callApi(
      "/count",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      callback
    );
  }
}
